export enum ShipmentStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SHIPMENT_IN_PROGRESS = 'SHIPMENT_IN_PROGRESS',
  PICKUP_SUCCESS = 'PICKUP_SUCCESS',
  DELIVERY_SUCCESS = 'DELIVERY_SUCCESS',
}

export enum SummariesStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
