export enum ShipmentState {
  SHIPMENT_PLAN_SENT = 'SHIPMENT_PLAN_SENT',
  PICKUP_SUCCESS = 'PICKUP_SUCCESS',
  DELIVERY_SUCCESS = 'DELIVERY_SUCCESS',
  POD_SUBMITTED = 'POD_SUBMITTED',
  POD_SENT = 'POD_SENT',
}
